-- V2__sample_data.sql - Sample data for catalogo service
INSERT INTO producto (nombre, descripcion, precio, imagen_url, disponible, categoria) VALUES
('Taco de Pastor', 'Carne de cerdo marinada con achiote, piña asada, cebolla y cilantro.', 28.00, 'assets/taco-pastor.jpg', true, 'TACOS'),
('Taco de Suadero', 'Suadero frito y jugoso, cebolla, cilantro y salsa verde.', 25.00, 'assets/taco-suadero.jpg', true, 'TACOS'),
('Taco de Bistec', 'Bistec de res a la plancha, cebolla asada, chile de árbol al gusto.', 30.00, 'assets/taco-bistec.jpg', true, 'TACOS'),
('Taco de Tripa', 'Tripa de res bien dorada y crujiente, cebolla, cilantro y limón.', 22.00, 'assets/taco-tripa.jpg', false, 'TACOS'),
('Taco de Longaniza', 'Longaniza de cerdo casera, cebolla, cilantro y salsa roja.', 26.00, 'assets/taco-longaniza.jpg', true, 'TACOS'),
('Taco de Chorizo', 'Chorizo mexicano, papa, cebolla y cilantro.', 27.00, 'assets/taco-chorizo.jpg', true, 'TACOS'),
('Taco de Barbacoa', 'Barbacoa de borrego, consomé, cebolla, cilantro y limón.', 35.00, 'assets/taco-barbacoa.jpg', true, 'TACOS'),
('Taco de Carnitas', 'Carnitas de cerdo estilo Michoacán, cebolla, cilantro y salsa.', 32.00, 'assets/taco-carnitas.jpg', true, 'TACOS'),
('Taco de Pescado', 'Pescado empanizado estilo Baja, col, crema y salsa chipotle.', 38.00, 'assets/taco-pescado.jpg', true, 'TACOS'),
('Taco de Camarón', 'Camarones al ajillo, col, aguacate y salsa de mango habanero.', 42.00, 'assets/taco-camaron.jpg', true, 'TACOS'),
('Quesadilla de Flor de Calabaza', 'Tortilla de maíz, flor de calabaza, queso Oaxaca y epazote.', 24.00, 'assets/quesadilla-flor.jpg', true, 'QUESADILLAS'),
('Quesadilla de Huitlacoche', 'Tortilla de maíz, huitlacoche, queso Oaxaca y epazote.', 26.00, 'assets/quesadilla-huitlacoche.jpg', true, 'QUESADILLAS'),
('Quesadilla de Champiñones', 'Tortilla de maíz, champiñones salteados, queso Oaxaca y epazote.', 23.00, 'assets/quesadilla-champinones.jpg', true, 'QUESADILLAS'),
('Quesadilla de Rajas', 'Tortilla de maíz, rajas con crema, queso Oaxaca y elote.', 25.00, 'assets/quesadilla-raja.jpg', true, 'QUESADILLAS'),
('Quesadilla de Chicharrón', 'Tortilla de maíz, chicharrón prensado, queso Oaxaca y salsa verde.', 27.00, 'assets/quesadilla-chicharron.jpg', true, 'QUESADILLAS'),
('Agua de Jamaica', 'Agua fresca de jamaica natural.', 18.00, 'assets/agua-jamaica.jpg', true, 'BEBIDAS'),
('Agua de Horchata', 'Agua fresca de horchata con canela.', 18.00, 'assets/agua-horchata.jpg', true, 'BEBIDAS'),
('Agua de Limón', 'Agua fresca de limón con chía.', 16.00, 'assets/agua-limon.jpg', true, 'BEBIDAS'),
('Coca Cola 600ml', 'Refresco Coca Cola 600ml.', 22.00, 'assets/coca-cola.jpg', true, 'BEBIDAS'),
('Sprite 600ml', 'Refresco Sprite 600ml.', 22.00, 'assets/sprite.jpg', true, 'BEBIDAS'),
('Cerveza Corona', 'Cerveza Corona 355ml.', 35.00, 'assets/corona.jpg', true, 'BEBIDAS'),
('Cerveza Modelo', 'Cerveza Modelo Especial 355ml.', 35.00, 'assets/modelo.jpg', true, 'BEBIDAS'),
('Flan Napolitano', 'Flan casero con cajeta.', 28.00, 'assets/flan.jpg', true, 'POSTRES'),
('Churros con Cajeta', 'Churros espolvoreados con azúcar y cajeta.', 32.00, 'assets/churros.jpg', true, 'POSTRES'),
('Gelato de Vainilla', 'Helado artesanal de vainilla con chispas de chocolate.', 30.00, 'assets/gelato.jpg', true, 'POSTRES');