spring.application.name=api-gateway
server.port=8080
spring.datasource.url=${DATABASE_URL:}
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka
eureka.instance.prefer-ip-address=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:9000}
management.endpoints.web.exposure.include=health,info
resilience4j.timelimiter.instances.reportes.timeout-duration=60s
resilience4j.circuitbreaker.instances.reportes.sliding-window-size=10
resilience4j.circuitbreaker.instances.reportes.failure-rate-threshold=80
resilience4j.circuitbreaker.instances.reportes.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.reportes.permitted-number-of-calls-in-half-open-state=2
spring.mvc.async.request-timeout=60000
